apiVersion: v1
data:
  MYSQL_DATABASE: phonebook_db
  # MYSQL_PASSWORD: cloud123
  # MYSQL_ROOT_PASSWORD: admin123
  MYSQL_DATABASE_HOST: mysql-service
  MYSQL_USER: admin
  MYSQL_PORT: 3306
kind: ConfigMap
metadata:
  name: servers-cm
  namespace: default
